-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Appointments/db/appointment_event_type_assignments.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/appointment_event_type_assignments (
  aeta_type VARCHAR(32) NOT NULL,
  aeta_calendar VARCHAR(32) NOT NULL
);
