-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Appointments/db/appointments.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/appointments (
  app_guid VARCHAR(32) NOT NULL,
  app_calendar_guid VARCHAR(32) NOT NULL,
  app_title VARCHAR(255) NOT NULL,
  app_start BLOB NOT NULL,
  app_end BLOB NOT NULL,
  app_is_all_day SMALLINT NOT NULL,
  app_recurring VARCHAR(100) DEFAULT NULL,
  app_creator INTEGER NOT NULL,
  app_created_at BLOB NOT NULL,
  app_data CLOB NOT NULL,
  PRIMARY KEY(app_guid)
);
