-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/calendars_assignments.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/calendars_assignments (
  cala_calendar VARCHAR(32) NOT NULL,
  cala_user INTEGER DEFAULT NULL,
  PRIMARY KEY(cala_calendar)
);
