-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Appointments/db/appointment_event_types.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/appointment_event_types (
  aet_guid VARCHAR(32) NOT NULL,
  aet_name VARCHAR(255) NOT NULL,
  aet_description LONGTEXT NOT NULL,
  aet_created_at BINARY(14) NOT NULL,
  aet_creator INT NOT NULL,
  aet_data LONGTEXT NOT NULL,
  aet_is_system TINYINT NOT NULL,
  PRIMARY KEY(aet_guid)
) /*$wgDBTableOptions*/;
