-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Appointments/db/appointments.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE appointments (
  app_guid VARCHAR(32) NOT NULL,
  app_calendar_guid VARCHAR(32) NOT NULL,
  app_title VARCHAR(255) NOT NULL,
  app_start TIMESTAMPTZ NOT NULL,
  app_end TIMESTAMPTZ NOT NULL,
  app_is_all_day SMALLINT NOT NULL,
  app_recurring VARCHAR(100) DEFAULT NULL,
  app_creator INT NOT NULL,
  app_created_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(app_guid)
);
