-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Appointments/db/appointment_participant_assignments.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE appointment_participant_assignments (
  apa_app VARCHAR(32) NOT NULL,
  ap_participant INT NOT NULL,
  PRIMARY KEY(apa_app, ap_participant)
);
