-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Appointments/db/appointment_participants.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE appointment_participants (
  ap_id SERIAL NOT NULL,
  ap_key VARCHAR(255) NOT NULL,
  ap_value VARCHAR(255) NOT NULL,
  PRIMARY KEY(ap_id)
);

CREATE UNIQUE INDEX ap_key_value_idx ON appointment_participants (ap_key, ap_value);
