-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Appointments/db/appointment_event_types.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE appointment_event_types (
  aet_guid VARCHAR(32) NOT NULL,
  aet_name VARCHAR(255) NOT NULL,
  aet_description TEXT NOT NULL,
  aet_created_at TIMESTAMPTZ NOT NULL,
  aet_creator INT NOT NULL,
  aet_data TEXT NOT NULL,
  aet_is_system SMALLINT NOT NULL,
  PRIMARY KEY(aet_guid)
);
