-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Appointments/db/calendars.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE calendars (
  cal_guid VARCHAR(32) NOT NULL,
  cal_name VARCHAR(255) NOT NULL,
  cal_description TEXT NOT NULL,
  cal_created_at TIMESTAMPTZ NOT NULL,
  cal_creator INT NOT NULL,
  cal_wiki_id VARCHAR(255) NOT NULL,
  PRIMARY KEY(cal_guid)
);
